beer<-read.csv("beer.csv",header=T,dec=",",sep=";");
beer<-ts(beer[,1],start=1956,freq=12);
plot(stl(log(beer),s.window="periodic"))
lbeer<-log(beer);
t<-seq(1956,1995.2,length=length(beer))
t
t2<-t^2
plot(lbeer)
lm(lbeer~t+t2)
lines(lm(lbeer~t+t2)$fit,col=2,lwd=2)
plot(lbeer)
lines(lm(lbeer~t+t2)$fit,col=2,lwd=2)
sin.t<-sin(2*pi*t)
cos.t<-cos(2*pi*t)
lines(lm(lbeer~t+t2+sin.t+cos.t)$fit,col=4)
sinCosSquareLM=lm(lbeer~t+t2+sin.t+cos.t)
sinCosSquareLM$fit
lines(lm(lbeer~t+t2+sin.t+cos.t)$fit,col=4)
lines(sinCosSquareLM$fit,col=4)
summary(sinCosSquareLM)
hw=HoltWinters(beer)
hw$fit
hw$fit[,1]
sqrt(sum((beer-hw$fit[,1])^2))/length(beer)
plot(beer)
lines(HoltWinters(beer)$fitted,col="red")
lines(hw$fitted,col="red")
plot(hw$fitted,col="red")
lines(predict(hw,n.ahead=48),col=2)
beer.ar<-arima(beer,order=c(4,0,0))
beer.ar.predict=predict(beer.ar,n.ahead=48)
beer.ar.predict
beer.ar.predict$pred
beer.arma<-arima(beer,order=c(2,0,2))
beer.arma
#not easy to get the fit from arima modeling
